package codehelp;

public class day2_Java_program_execution {
    static void main() {
//        program execution
        //user code -> compiler -> byte code -> JVM(java development machine) -> machine code -> machine

        //compiler :- A compiler is a software program that translates source code written in a programming language into machine
        //code or another form that a computer can execute.

        // byte code:- Bytecode is an intermediate code generated by a compiler. It is not directly understood by the
        // computer's CPU; instead, it is executed by a virtual machine.

        // JVM :- JVM (Java Virtual Machine) is a program that runs Java bytecode (.class files) on your computer.
        //Think of it as a translator + runtime environment between Java bytecode and your computer.

        // JRE :- JRE (Java Runtime Environment) is a software package that provides everything needed to run Java
        // applications on a computer. (JVM + library)

        // JDK :- JDK (Java Development Kit) is a software package used to develop, compile, debug, and run Java programs.

        //scale :- jvm < jre < jdk
    }
}
